(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.S2SCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='1.6';
const STORAGE_KEY='safe2spend_mvp14';
const DAY=86400000;
const n=v=>Math.max(0,Number(String(v??'').replace(/[$,\s]/g,''))||0);
const iso=d=>{const x=new Date(d);x.setHours(12,0,0,0);return x.toISOString().slice(0,10)};
const parseDate=s=>{if(!s)return null;const p=String(s).slice(0,10).split('-').map(Number);if(p.length!==3||!p[0])return null;return new Date(p[0],p[1]-1,p[2],12)};
const addDays=(d,days)=>{const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()+days);return x};
const today=()=>{const x=new Date();x.setHours(12,0,0,0);return x};
function defaultState(){return {stateVersion:VERSION,onboardingComplete:false,checking:0,cash:0,savings:0,payFreq:'weekly',nextPayday:'',payDays:['15','last'],paycheck:0,bills:[],everydayAmount:0,goalName:'',goalAmount:0,savePerPaycheck:0,savePace:'balanced',s2sBalance:null,s2sActivity:[],prePaydayAdjustments:[],lastProcessedPayday:null,lastS2SReason:'initial',updatedAt:null};}
function migrateState(raw){const d=defaultState(),x=raw&&typeof raw==='object'?raw:{};const life=x.life||{};const everyday=n(x.everydayAmount||x.everydayInput?.amount)||(n(life.food)+n(life.gas)+n(life.other));const bills=Array.isArray(x.bills)?x.bills.filter(b=>n(b.amount)&&b.nextDue).map((b,i)=>({id:b.id||`bill-${i+1}`,name:String(b.name||'Bill'),amount:n(b.amount),nextDue:String(b.nextDue).slice(0,10),freq:b.freq||'monthly'})):[];const configured=!!x.onboardingComplete||(n(x.paycheck)>0&&!!x.nextPayday&&(bills.length>0||everyday>0||n(x.checking)+n(x.cash)+n(x.savings)>0));return {...d,...x,stateVersion:VERSION,onboardingComplete:configured,checking:n(x.checking),cash:n(x.cash),savings:n(x.savings),paycheck:n(x.paycheck),bills,everydayAmount:everyday,goalName:String(x.goalName||''),goalAmount:n(x.goalAmount),savePerPaycheck:n(x.savePerPaycheck),s2sBalance:x.s2sBalance===null||x.s2sBalance===undefined?null:n(x.s2sBalance),s2sActivity:Array.isArray(x.s2sActivity)?x.s2sActivity.slice(0,50):[],prePaydayAdjustments:Array.isArray(x.prePaydayAdjustments)?x.prePaydayAdjustments.slice(0,50):[],payDays:Array.isArray(x.payDays)&&x.payDays.length===2?x.payDays:['15','last']};}
function loadState(storage){if(!storage)return defaultState();let raw=null;try{raw=JSON.parse(storage.getItem(STORAGE_KEY)||'null')}catch(e){try{storage.removeItem(STORAGE_KEY)}catch(_){ }return defaultState()}if(!raw)return defaultState();const s=migrateState(raw);if(!s.onboardingComplete){try{storage.removeItem(STORAGE_KEY)}catch(_){ }return defaultState()}return s;}
function saveState(storage,state){const s=migrateState(state);s.onboardingComplete=!!state.onboardingComplete;s.updatedAt=new Date().toISOString();const errs=validateState(s);if(errs.length)throw new Error('State invariant failed: '+errs.join('; '));if(storage&&s.onboardingComplete)storage.setItem(STORAGE_KEY,JSON.stringify(s));return s;}
function advanceDate(date,freq){const d=new Date(date);d.setHours(12,0,0,0);if(freq==='weekly')d.setDate(d.getDate()+7);else if(freq==='biweekly')d.setDate(d.getDate()+14);else if(freq==='quarterly')d.setMonth(d.getMonth()+3);else if(freq==='yearly')d.setFullYear(d.getFullYear()+1);else d.setMonth(d.getMonth()+1);return d;}
function nextPayDates(state,count=12,from=today()){let out=[];let d=parseDate(state.nextPayday);if(!d)return out;const f=state.payFreq||'weekly';if(f==='semimonthly'){let cursor=new Date(from);cursor.setHours(12,0,0,0);const dayVal=v=>v==='last'?new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate():Math.min(n(v),new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate());while(out.length<count){for(const token of state.payDays||['15','last']){const cand=new Date(cursor.getFullYear(),cursor.getMonth(),dayVal(token),12);if(cand>=from&&(!out.length||cand>out[out.length-1]))out.push(cand);if(out.length>=count)break}cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1,12)}return out}
 while(d<from)d=advanceDate(d,f);for(let i=0;i<count;i++){out.push(new Date(d));d=advanceDate(d,f)}return out;}
function nextBillDue(bill,from){let d=parseDate(bill.nextDue);if(!d)return null;while(d<from)d=advanceDate(d,bill.freq||'monthly');return d;}
function billFundingForPaycheck(state,payDate){const pd=new Date(payDate);pd.setHours(12,0,0,0);const details=[];for(const b of state.bills||[]){const due=nextBillDue(b,pd);if(!due)continue;const pays=nextPayDates(state,60,pd).filter(x=>x<=due);const count=Math.max(1,pays.length);const amount=n(b.amount)/count;details.push({id:b.id,name:b.name,amount,due:iso(due),billAmount:n(b.amount),paychecksRemaining:count});}return {details,total:details.reduce((s,x)=>s+x.amount,0)};}
function projectedAdjustmentForPayday(state,pd){const key=iso(pd);return (state.prePaydayAdjustments||[]).filter(x=>x.payday===key).reduce((sum,x)=>sum+n(x.amount),0)}
function calculateNextPaycheck(state,from=today()){const pd=nextPayDates(state,1,from)[0];if(!pd)return {date:null,income:0,billReserve:0,billDetails:[],everyday:0,savingsTransfer:0,prePaydayAdjustment:0,projectedSafe2Spend:0};const funding=billFundingForPaycheck(state,pd),income=n(state.paycheck),everyday=Math.min(n(state.everydayAmount),Math.max(0,income-funding.total)),savingsTransfer=Math.min(n(state.savePerPaycheck),Math.max(0,income-funding.total-everyday)),adj=projectedAdjustmentForPayday(state,pd),projected=Math.max(0,income-funding.total-everyday-savingsTransfer-adj);return {date:iso(pd),income,billReserve:funding.total,billDetails:funding.details,everyday,savingsTransfer,prePaydayAdjustment:adj,projectedSafe2Spend:projected};}
function suggestedCurrentSafe(state,from=today()){const available=n(state.checking)+n(state.cash),next=calculateNextPaycheck(state,from),required=next.billReserve+next.everyday+next.savingsTransfer;return Math.max(0,available-required);}
function calculateCurrent(state,from=today()){const available=n(state.checking)+n(state.cash);const safe=state.s2sBalance===null||state.s2sBalance===undefined?suggestedCurrentSafe(state,from):Math.min(available,n(state.s2sBalance));return {availableBalance:available,accountedFor:Math.max(0,available-safe),safe2Spend:safe,savingsBalance:n(state.savings)};}
function calculatePlan(state,from=today()){const current=calculateCurrent(state,from),nextPaycheck=calculateNextPaycheck(state,from);return {current,nextPaycheck,zeroState:deriveZeroState(state,current,nextPaycheck,from)};}
function deriveZeroState(state,current,next,from=today()){if(current.safe2Spend>0)return 'positive';if(state.lastS2SReason==='spent_to_zero'||state.lastS2SReason==='saved_to_zero')return 'exhausted';if(next.projectedSafe2Spend>0)return 'between';return 'fully_allocated';}
function currentProtectionGap(state,from=today()){const c=calculateCurrent(state,from),next=calculateNextPaycheck(state,from),required=next.billReserve+next.everyday+next.savingsTransfer;return Math.max(0,required-c.accountedFor);}
function adjustAvailable(state,delta){let s={...state};if(delta>=0){s.checking=n(s.checking)+delta;return s}let left=Math.abs(delta),take=Math.min(n(s.checking),left);s.checking=n(s.checking)-take;left-=take;if(left>0)s.cash=Math.max(0,n(s.cash)-left);return s;}
function pushActivity(state,item){const a=[{id:`a-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,date:new Date().toISOString(),...item},...(state.s2sActivity||[])].slice(0,50);return {...state,s2sActivity:a};}
function spend(state,amount,note='Spent',from=today()){let s=migrateState(state);const c=calculateCurrent(s,from),amt=Math.min(n(amount),c.safe2Spend,c.availableBalance);if(!amt)return s;s=adjustAvailable(s,-amt);s.s2sBalance=Math.max(0,c.safe2Spend-amt);s.lastS2SReason=s.s2sBalance<=.001?'spent_to_zero':'spent';s=pushActivity(s,{type:'spend',amount:amt,note});return s;}
function saveFromSafe(state,amount,note='Moved to savings',from=today()){let s=migrateState(state);const c=calculateCurrent(s,from),amt=Math.min(n(amount),c.safe2Spend,c.availableBalance);if(!amt)return s;s=adjustAvailable(s,-amt);s.savings=n(s.savings)+amt;s.s2sBalance=Math.max(0,c.safe2Spend-amt);s.lastS2SReason=s.s2sBalance<=.001?'saved_to_zero':'saved';s=pushActivity(s,{type:'save',amount:amt,note});return s;}
function moneyIn(state,amount,mode='decide',note='Money in',from=today()){let s=migrateState(state),amt=n(amount);if(!amt)return s;if(mode==='save'){s.savings=n(s.savings)+amt;s=pushActivity(s,{type:'save',amount:amt,note,mode});return s}const before=calculateCurrent(s,from),gap=currentProtectionGap(s,from);s=adjustAvailable(s,amt);let flex=mode==='flex'?amt:Math.max(0,amt-Math.min(amt,gap));s.s2sBalance=Math.min(calculateCurrent(s,from).availableBalance,before.safe2Spend+flex);s.lastS2SReason='money_in';s=pushActivity(s,{type:'add',amount:amt,note,mode});return s;}
function billsDueBefore(state,endDate,from=today()){if(!endDate)return 0;const end=new Date(endDate);let total=0;for(const b of state.bills||[]){let d=nextBillDue(b,from);while(d&&d<=end){total+=n(b.amount);d=advanceDate(d,b.freq||'monthly')}}return total;}
function prePaydayCapacity(state,from=today()){const plan=calculatePlan(state,from),pd=parseDate(plan.nextPaycheck.date);if(!pd)return 0;const dayBefore=addDays(pd,-1),hard=billsDueBefore(state,dayBefore,from),freeAfterHard=Math.max(0,plan.current.availableBalance-hard);return Math.max(0,Math.min(freeAfterHard,plan.nextPaycheck.projectedSafe2Spend));}
function spendBeforePayday(state,amount,note='Spent before payday',from=today()){let s=migrateState(state),cap=prePaydayCapacity(s,from),amt=Math.min(n(amount),cap,calculateCurrent(s,from).availableBalance);if(!amt)return s;const next=calculateNextPaycheck(s,from);s=adjustAvailable(s,-amt);s.prePaydayAdjustments=[{payday:next.date,amount:amt,note,date:new Date().toISOString()},...(s.prePaydayAdjustments||[])].slice(0,50);s.lastS2SReason='prepayday';s=pushActivity(s,{type:'spend',amount:amt,note,mode:'prepayday'});return s;}
function processPayday(state,from=today()){let s=migrateState(state);const plan=calculateNextPaycheck(s,from);if(!plan.date||plan.date!==iso(from)||n(s.paycheck)<=0||s.lastProcessedPayday===plan.date)return {state:s,processed:false};const before=calculateCurrent(s,from);s=adjustAvailable(s,plan.income);s.s2sBalance=Math.min(calculateCurrent(s,from).availableBalance,before.safe2Spend+plan.projectedSafe2Spend);s.lastProcessedPayday=plan.date;s.prePaydayAdjustments=(s.prePaydayAdjustments||[]).filter(x=>x.payday!==plan.date);s=pushActivity(s,{type:'add',amount:plan.income,note:'Paycheck',mode:'paycheck',safeAdded:plan.projectedSafe2Spend,system:true});const current=parseDate(s.nextPayday);if(current){if(s.payFreq==='semimonthly'){const candidates=nextPayDates({...s,nextPayday:iso(addDays(from,1))},1,addDays(from,1));s.nextPayday=candidates[0]?iso(candidates[0]):s.nextPayday}else s.nextPayday=iso(advanceDate(current,s.payFreq||'weekly'))}s.lastS2SReason='payday';return {state:s,processed:true};}
function reanchor(state,from=today()){let s=migrateState(state);s.s2sBalance=suggestedCurrentSafe(s,from);s.lastS2SReason='reanchor';return s;}
function validateState(state,from=today()){const s=migrateState(state),errs=[],p=calculatePlan(s,from),c=p.current;if(Math.abs((c.accountedFor+c.safe2Spend)-c.availableBalance)>.01)errs.push('Available Balance != Accounted For + Safe2Spend');if(c.safe2Spend>c.availableBalance+.01)errs.push('Safe2Spend exceeds Available Balance');if(n(s.savings)<0)errs.push('Savings negative');const np=p.nextPaycheck;const split=np.billReserve+np.everyday+np.savingsTransfer+np.prePaydayAdjustment+np.projectedSafe2Spend;if(np.income&&Math.abs(split-np.income)>.02)errs.push('Projected paycheck split does not equal paycheck');if((s.s2sActivity||[]).length>50)errs.push('Activity history exceeds 50');if((s.prePaydayAdjustments||[]).length>50)errs.push('Pre-payday adjustments exceed 50');return errs;}
function runInvariantTests(){const results=[];const test=(name,fn)=>{try{fn();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.message})}};const eq=(a,b,msg)=>{if(Math.abs(a-b)>.02)throw new Error(msg+` (${a} != ${b})`)};const base={...defaultState(),onboardingComplete:true,checking:120,savings:3000,payFreq:'weekly',nextPayday:'2026-09-10',paycheck:1270,bills:[{id:'rent',name:'Rent',amount:2000,nextDue:'2026-09-30',freq:'monthly'},{id:'car',name:'Car',amount:750,nextDue:'2026-10-08',freq:'monthly'},{id:'ins',name:'Insurance',amount:170,nextDue:'2026-09-28',freq:'monthly'},{id:'phone',name:'Phone',amount:70,nextDue:'2026-09-30',freq:'monthly'}],everydayAmount:143,savePerPaycheck:140,s2sBalance:0};const now=new Date(2026,8,9,12);
 test('Available = Accounted + Current S2S',()=>{const c=calculateCurrent(base,now);eq(c.availableBalance,c.accountedFor+c.safe2Spend,'decomposition')});
 test('Savings survives engine views',()=>{eq(calculatePlan(base,now).current.savingsBalance,3000,'savings')});
 test('Projected split sums to paycheck',()=>{const x=calculateNextPaycheck(base,now);eq(x.income,x.billReserve+x.everyday+x.savingsTransfer+x.prePaydayAdjustment+x.projectedSafe2Spend,'paycheck split')});
 test('Current and projected are distinct',()=>{const p=calculatePlan(base,now);if(p.current.safe2Spend===p.nextPaycheck.projectedSafe2Spend)throw new Error('current silently equals projected')});
 test('Zero + positive projected => between',()=>{if(calculatePlan(base,now).zeroState!=='between')throw new Error('wrong zero state')});
 test('Spend/save conservation',()=>{let s={...base,checking:500,s2sBalance:200};s=spend(s,40,'Gas',now);eq(calculateCurrent(s,now).availableBalance,460,'spend available');eq(calculateCurrent(s,now).safe2Spend,160,'spend safe');s=saveFromSafe(s,60,'Emergency',now);eq(calculateCurrent(s,now).availableBalance,400,'save available');eq(s.savings,3060,'save savings');eq(calculateCurrent(s,now).safe2Spend,100,'save safe')});
 test('Money-in decide repairs protection before flexibility',()=>{let s={...base,checking:0,s2sBalance:0};const gap=currentProtectionGap(s,now);s=moneyIn(s,gap+50,'decide','Side gig',now);eq(calculateCurrent(s,now).safe2Spend,50,'decide flex')});
 test('Payday posts once',()=>{const pd=new Date(2026,8,10,12);let a=processPayday(base,pd);if(!a.processed)throw new Error('first payday not processed');const bal=calculateCurrent(a.state,pd).availableBalance;let b=processPayday(a.state,pd);if(b.processed)throw new Error('second payday processed');eq(calculateCurrent(b.state,pd).availableBalance,bal,'double post')});
 test('No render-time anchor mutation required',()=>{const a=JSON.stringify(base),p=calculatePlan(base,now);if(JSON.stringify(base)!==a)throw new Error('calculatePlan mutated state');if(!p.current)throw new Error('missing current')});
 return {pass:results.every(x=>x.pass),results};}
return {VERSION,STORAGE_KEY,n,iso,parseDate,addDays,today,defaultState,migrateState,loadState,saveState,nextPayDates,billFundingForPaycheck,calculateCurrent,calculateNextPaycheck,calculatePlan,deriveZeroState,suggestedCurrentSafe,currentProtectionGap,spend,saveFromSafe,moneyIn,prePaydayCapacity,spendBeforePayday,processPayday,reanchor,validateState,runInvariantTests};
});